### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by mgeigenberger** [Florian-Jungwirth/2223-4ahitm-project-lowco#5]
Ich als Entwickler möchte, dass bei meinen Commits auf dem Main-Branch das Projekt automatisch neu gebaut und veröffentlicht wird, um stets auf eine aktuelle Version der Anwendung zugreifen zu können.

Definition of done:
Github Actions wurde so konfiguriert, dass das Projekt bei jedem Commit auf dem Main-Branch automatisch neu gebau und veröffentlicht wird.

**Comment by Florian-Jungwirth** [comment]
Gegeben:
Unser fehlerfreier Sourcecode.

Wenn:
Wenn ich etwas ändere, das ich commite und pushe.

Dann:
Kann ich eine .exe in den Releases herunterladen, die ausführbar ist und die Änderungen enthält. Es soll erkennbar sein, dass es eine neue Version ist.
